In [179]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [221]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]], dtype=torch.float32)
y = torch.tensor([[3],[7],[11],[15]], dtype=torch.float32)

In [264]:
model = nn.Sequential(
    nn.Linear(2, 8),
    nn.Sigmoid(),
    nn.Linear(8, 1),
)

print([p for p in model.parameters()])

[Parameter containing:
tensor([[-0.0581, -0.2394],
        [-0.4062,  0.3812],
        [ 0.0684,  0.2290],
        [ 0.2360,  0.3211],
        [-0.5323,  0.5804],
        [ 0.0168, -0.4868],
        [-0.1969, -0.2733],
        [-0.6747, -0.3833]], requires_grad=True), Parameter containing:
tensor([ 0.2589, -0.7014, -0.6268,  0.2970, -0.0227, -0.4479,  0.0107,  0.4246],
       requires_grad=True), Parameter containing:
tensor([[-0.1974,  0.1040,  0.2249,  0.1029, -0.2470,  0.1550,  0.0436,  0.0882]],
       requires_grad=True), Parameter containing:
tensor([-0.2140], requires_grad=True)]


In [266]:
class CustomDataSet(Dataset):
    def __init__(self, x, y):
        super().__init__()
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, i):
        return self.x[i], self.y[i]

dataset = CustomDataSet(x, y)
data_loader = DataLoader(dataset, 64, shuffle=True)

In [304]:
epochs = 10000
loss_fn = nn.MSELoss()
lr = 0.001
opt = optim.SGD(model.parameters(), lr)

for i in range(epochs):
    for data, targets in data_loader:
        _targets = model(data)
        loss = loss_fn(_targets, targets)

        opt.zero_grad()
        loss.backward()
        opt.step()

        if i % 100 == 0: print(loss)

tensor(0.0066, grad_fn=<MseLossBackward0>)
tensor(0.0065, grad_fn=<MseLossBackward0>)
tensor(0.0065, grad_fn=<MseLossBackward0>)
tensor(0.0064, grad_fn=<MseLossBackward0>)
tensor(0.0064, grad_fn=<MseLossBackward0>)
tensor(0.0063, grad_fn=<MseLossBackward0>)
tensor(0.0062, grad_fn=<MseLossBackward0>)
tensor(0.0062, grad_fn=<MseLossBackward0>)
tensor(0.0061, grad_fn=<MseLossBackward0>)
tensor(0.0061, grad_fn=<MseLossBackward0>)
tensor(0.0060, grad_fn=<MseLossBackward0>)
tensor(0.0060, grad_fn=<MseLossBackward0>)
tensor(0.0059, grad_fn=<MseLossBackward0>)
tensor(0.0059, grad_fn=<MseLossBackward0>)
tensor(0.0058, grad_fn=<MseLossBackward0>)
tensor(0.0058, grad_fn=<MseLossBackward0>)
tensor(0.0057, grad_fn=<MseLossBackward0>)
tensor(0.0057, grad_fn=<MseLossBackward0>)
tensor(0.0056, grad_fn=<MseLossBackward0>)
tensor(0.0056, grad_fn=<MseLossBackward0>)
tensor(0.0055, grad_fn=<MseLossBackward0>)
tensor(0.0055, grad_fn=<MseLossBackward0>)
tensor(0.0055, grad_fn=<MseLossBackward0>)
tensor(0.00

In [286]:
from torchsummary import summary

summary(model, torch.zeros(1,2))


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─Sigmoid: 1-2                           [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─Sigmoid: 1-2                           [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [306]:
val = torch.tensor([[5, 10], [30, 6], [1, 1], [1.5, 2.5], [1,2]])

model(val)

tensor([[ 5.8206],
        [19.1826],
        [ 3.8201],
        [ 3.9699],
        [ 3.0309]], grad_fn=<AddmmBackward0>)

In [310]:
torch.save(model.to(device=torch.device('cpu')).state_dict(), "./hi.pth")

In [318]:
model.load_state_dict(torch.load("./hi.pth", weights_only=True))

val = torch.tensor([[5, 10], [30, 6], [1, 1], [1.5, 2.5], [1,2]])

model(val)

tensor([[ 5.8206],
        [19.1826],
        [ 3.8201],
        [ 3.9699],
        [ 3.0309]], grad_fn=<AddmmBackward0>)