In [24]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F

In [59]:
img = torch.tensor([
    [1, 2, 3, 5, 6],
    [7, 8, 9, 10, 11],
    [12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21],
    [22, 23, 24, 25, 26],
])

kernel = torch.tensor([
    [1, 2],
    [3, 4],
])

img = img[None][None]
kernel = kernel[None][None]

result = F.conv2d(img, kernel, stride=2, padding=2)
max = F.max_pool2d(result, 2)

result, max

(tensor([[[[  0,   0,   0,   0],
           [  0,  58,  80,  39],
           [  0, 161, 181,  79],
           [  0,  68,  74,  26]]]]),
 tensor([[[[ 58,  80],
           [161, 181]]]]))

In [62]:
max.flatten()

tensor([ 58,  80, 161, 181])